import Head from 'next/head'
import {
  Text,
  Heading,
  Image,
  Button,
  Container,
  Stack,
  Flex,
} from "@chakra-ui/react";
import NextLink from "next/link";
import Hero from '@/components/Hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>Sitecore Blok Next.js Starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex as="main" height='calc(100vh)' background={'chakra-body-bg'} >
        <Hero />
      <NextLink href="https://www.sitecore.com">
        <Image
          m="8"
          h="10"
          src="sitecore.svg"
          alt="Sitecore logo"
          position={'absolute'}
          bottom={'0'}
          right={'0'}
          />
        </NextLink>
    </Flex>
    </>
  )
}
