import Head from "next/head";
import {
Box,
  Container,
  Flex,
  ContainerProps,
  Text,
} from "@chakra-ui/react";
import { motion } from "framer-motion";
import React, { ReactNode } from "react";
import NavBar from "@/components/Navbar";

type PageProps = {
  title?: string;
  description?: string;
  children: ReactNode;
};

const MotionContainer = motion<ContainerProps>(Container);

export default function PageLayout({ title, description, children }: PageProps) {
  return (
    <>
      <Head>
        <title>{title ?? "Sitecore Blok Next.js Starter"}</title>
        <meta name="description" content={description ?? "Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexFlow="column nowrap" minH={"100vh"}>
        <NavBar />
        <Flex flexGrow={1} as="main">
          {/* <MotionContainer
            display="flex"
            maxW="full"
            minH={{ base: "auto", md: "100%" }}
            flexGrow={1}
            overflow="hidden"
          > */}
            {children}
          {/* </MotionContainer> */}
        </Flex>

        <Box p="4">
            <Text>© Copyright 2023, Sitecore. All Rights Reserved</Text>
        </Box>
              
      </Flex>
    </>
  );
}
